services:

  mysql:
    image: mysql:8.4
    container_name: docwallet_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: docwallet_backend
    restart: unless-stopped
    environment:
      SERVER_PORT: "8080"

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}

      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 20MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 20MB

    depends_on:
      - mysql

  frontend:
    build:
      context: ./docwallet_frontend
      dockerfile: Dockerfile
    container_name: docwallet_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: